dataset= 'CULane'
data_root= '/media/walnutadmin/Darryl_USyd/Lane_Detection/CULane_cropped_left/' # Need to be modified before running
epoch= 50
batch_size= 34
optimizer= 'SGD'
learning_rate = 0.00625
weight_decay = 0.0001
momentum= 0.9
scheduler= 'multi'
steps= [25,38]
gamma= 0.1
warmup= 'linear'
warmup_iters= 695
use_aux= False  #usar auxiliary segmentation branch (default False)
griding_num= 200
backbone= '34'
sim_loss_w= 0.0
shp_loss_w= 0.0
note= ''
log_path= '' #'/media/walnutadmin/Darryl_USyd/Lane_Detection/logs'
finetune= None #'/home/its/Hector/repos/Dihn/Ultra-Fast-Lane-Detection-v2/weights/culane_res34.pth'#None #'/home/its/Hector/repos/Ultra-Fast-Lane-Detection-v2/weights/culane_res34.pth'
resume= None #'/home/its/Hector/repos/Dihn/Ultra-Fast-Lane-Detection-v2/weights/culane_res34.pth' #'/home/its/Hector/repos/Ultra-Fast-Lane-Detection-v2/weights/ep003.pth'
test_model= '' #'/home/its/Hector/repos/Ultra-Fast-Lane-Detection-v2/weights/culane_res34.pth'
test_work_dir = '/home/its/Hector/work'
tta=False
num_lanes= 2
var_loss_power= 2.0
auto_backup= True
num_row= 72
num_col= 81
train_width= 1600
train_height= 320
num_cell_row= 100
num_cell_col= 200
mean_loss_w= 0.05
fc_norm= True
crop_ratio = 1
